# Generated by Django 5.1.7 on 2025-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('标题', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('总价', models.CharField(default='', max_length=50, verbose_name='总价(万)')),
                ('面积', models.CharField(default='', max_length=50, verbose_name='面积(㎡)')),
                ('装修', models.CharField(default='', max_length=50, verbose_name='装修')),
                ('楼层', models.CharField(default='', max_length=50, verbose_name='楼层')),
                ('年份', models.CharField(default='', max_length=50, verbose_name='年份')),
                ('小区', models.CharField(default='', max_length=50, verbose_name='小区')),
                ('区域', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('关注量', models.CharField(default='', max_length=50, verbose_name='关注量')),
                ('发布时间', models.CharField(default='', max_length=50, verbose_name='发布时间')),
                ('户型', models.CharField(default='', max_length=50, verbose_name='户型')),
                ('单价', models.CharField(default='', max_length=50, verbose_name='单价(元/平)')),
                ('朝向', models.CharField(default='', max_length=50, verbose_name='朝向')),
                ('结构', models.CharField(default='', max_length=50, verbose_name='结构')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
